### ISSUE TITLE
escape character multiplication

### ISSUE THREAD

**Issue by BaronVladziu** [SimGus/Chatette#24]
I think I found a small bug regarding escape character. I created this simple `master.chatette` file:
```
%[&a\/b]
    hello
```
and used command:
```
python -m chatette -f "master.chatette"
```
Generated output should be:
```
{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "entities": [],
        "intent": "a/b",
        "text": "hello"
      },
      {
        "entities": [],
        "intent": "a/b",
        "text": "Hello"
      }
    ],
    "entity_synonyms": [],
    "lookup_tables": [],
    "regex_features": []
  }
}
```
but it is:
```
{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "entities": [],
        "intent": "a\\/b",
        "text": "hello"
      },
      {
        "entities": [],
        "intent": "a\\/b",
        "text": "Hello"
      }
    ],
    "entity_synonyms": [],
    "lookup_tables": [],
    "regex_features": []
  }
}
```

I use command:
```
sed -i 's/\\\\\//\//g' "output/train/output.json"
```
as a workaround.

**Thanks for creating this tool. It's awesome!**

**Comment by SimGus** [comment]
Indeed, that is not the intended behavior. I will fix that as soon as I can.

Thanks for the reporting this :)

**Comment by SimGus** [comment]
This is fixed on `dev` branch and will be present in the next patch version

**Comment by SimGus** [comment]
The newest version of Chatette (v1.6.1) has just been released with this fix included!

**Comment by TatianaParshina** [comment]
@SimGus  thank you for the fix! I still have an issue with the escape character. 
In my case I have 2 files:
1) `main.chatette`
```
%[intent_emails](5)
	My email address is @[slot_email]
|slots.chatette
```

2) `slots.chatette`

```
@[slot_email]
	aaa\@mail.com
```
I run script:
`python -m chatette main.chatette -a rasa-md -f
`
As a result:
`My email address is [aaa\@mail.com](slot_email)`

Expected result:
`My email address is [aaa@mail.com](slot_email)`

**Comment by SimGus** [comment]
@TatianaParshina there is indeed an issue with the fix I made, but it should be easy to fix. I'll fix that shortly.
Thank you for your very precise bug report :)

**Comment by SimGus** [comment]
This is fixed on `dev` branch. I also updated the documentation about escaping characters.
The fix will be included in the next version.
